// Copyright 2026 The FRUS Explorer Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

import Testing
import Foundation
@testable import FRUSExplorer

/// Tests for `IndexingPipeline.mergeReadingSequence`, the pure structure-plus-cache
/// merge that powers complete-volume Prev/Next navigation (front matter → body →
/// back matter), including the structured/navigation sections (Persons, Sources,
/// Table of Contents, Index) that the search index deliberately omits.
@Suite struct ReadingSequenceTests {

    /// Builds a representative volume: a `<front>` wrapper with TOC, preface, and
    /// persons sections; a compilation with two numbered documents; and a `<back>`
    /// wrapper with an index. Only the preface and the two documents are promoted to
    /// `document_cache` — TOC, persons, and index are not (mirroring the real indexer).
    private func sampleStructure(volumeId: String) -> VolumeStructure {
        let front = VolumeSection(
            sectionId: "front", divType: "front", title: "Front Matter",
            documentIds: [],
            subsections: [
                VolumeSection(sectionId: "toc", divType: "table-of-contents",
                              title: "Table of Contents", documentIds: [], subsections: []),
                VolumeSection(sectionId: "preface", divType: "preface",
                              title: "Preface", documentIds: [], subsections: []),
                VolumeSection(sectionId: "persons", divType: "persons",
                              title: "Persons", documentIds: [], subsections: []),
            ])
        let compilation = VolumeSection(
            sectionId: "comp1", divType: "compilation", title: "Compilation 1",
            documentIds: ["d1", "d2"], subsections: [])
        let back = VolumeSection(
            sectionId: "back", divType: "back", title: "Back Matter",
            documentIds: [],
            subsections: [
                VolumeSection(sectionId: "index", divType: "index",
                              title: "Index", documentIds: [], subsections: []),
            ])
        return VolumeStructure(volumeId: volumeId, sections: [front, compilation, back])
    }

    @Test("Merge yields the full volume in source order, including unindexed sections")
    func mergeFullVolumeOrder() {
        let vol = "frusTest"
        let cached = [
            DocumentBrowserEntry(documentId: "preface", volumeId: vol, header: "Preface (cached)"),
            DocumentBrowserEntry(documentId: "d1", volumeId: vol, documentNumber: "1", header: "Doc 1"),
            DocumentBrowserEntry(documentId: "d2", volumeId: vol, documentNumber: "2", header: "Doc 2"),
        ]

        let result = IndexingPipeline.mergeReadingSequence(
            structure: sampleStructure(volumeId: vol), cached: cached, volumeId: vol)

        // TOC, persons, and index are reachable even though they are not indexed.
        #expect(result.map(\.documentId) == ["toc", "preface", "persons", "d1", "d2", "index"])
    }

    @Test("Promoted sections keep their cached metadata; synthesised ones use the title")
    func mergePreservesMetadata() {
        let vol = "frusTest"
        let cached = [
            DocumentBrowserEntry(documentId: "preface", volumeId: vol, header: "Preface (cached)"),
            DocumentBrowserEntry(documentId: "d1", volumeId: vol, documentNumber: "1", header: "Doc 1"),
            DocumentBrowserEntry(documentId: "d2", volumeId: vol, documentNumber: "2", header: "Doc 2"),
        ]

        let result = IndexingPipeline.mergeReadingSequence(
            structure: sampleStructure(volumeId: vol), cached: cached, volumeId: vol)
        let byId = Dictionary(uniqueKeysWithValues: result.map { ($0.documentId, $0) })

        // Cached entry wins for promoted sections.
        #expect(byId["preface"]?.header == "Preface (cached)")
        // Synthesised entry carries the section title and the volume id.
        #expect(byId["persons"]?.header == "Persons")
        #expect(byId["persons"]?.volumeId == vol)
    }

    @Test("Sections without an explicit xml:id are skipped (can't be reopened by id)")
    func mergeSkipsAutoGeneratedSectionIds() {
        let vol = "frusTest"
        // "preface-1" is the parser's auto-generated fallback id for an id-less div.
        let structure = VolumeStructure(volumeId: vol, sections: [
            VolumeSection(sectionId: "preface-1", divType: "preface",
                          title: "Preface", documentIds: [], subsections: []),
            VolumeSection(sectionId: "comp1", divType: "compilation", title: "C1",
                          documentIds: ["d1"], subsections: []),
        ])
        let cached = [DocumentBrowserEntry(documentId: "d1", volumeId: vol, header: "Doc 1")]

        let result = IndexingPipeline.mergeReadingSequence(
            structure: structure, cached: cached, volumeId: vol)

        #expect(result.map(\.documentId) == ["d1"])
    }

    @Test("Cached documents missing from the structure are still included (never lost)")
    func mergeAppendsUnreachedCachedDocuments() {
        let vol = "frusTest"
        // Structure references only d1; d3 exists in the cache but not the structure.
        let structure = VolumeStructure(volumeId: vol, sections: [
            VolumeSection(sectionId: "comp1", divType: "compilation", title: "C1",
                          documentIds: ["d1"], subsections: []),
        ])
        let cached = [
            DocumentBrowserEntry(documentId: "d1", volumeId: vol, header: "Doc 1"),
            DocumentBrowserEntry(documentId: "d3", volumeId: vol, header: "Doc 3"),
        ]

        let result = IndexingPipeline.mergeReadingSequence(
            structure: structure, cached: cached, volumeId: vol)

        #expect(result.map(\.documentId) == ["d1", "d3"])
    }
}
