// Copyright 2026 The FRUS Explorer Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

import CryptoKit
import Foundation
import Testing
@testable import FRUSExplorer

/// What happens on a device when the vector generation changes underneath it.
///
/// ## Reframed after the 256 → 512 move, on purpose
/// The first version of this suite rehearsed that specific transition: it asserted the shipped
/// artifacts were 256 and pointed at an out-of-repo 512 build through two environment variables.
/// The moment 512 shipped, both premises died — and because the suite **skipped itself** when the
/// variables were absent, it would have gone on passing while testing nothing. That is the failure
/// its own prints were added to expose, so the fix is not to update the numbers but to stop naming
/// them.
///
/// Everything below now derives from **whatever generation is bundled today**. The "previous"
/// generation is synthesised by changing the provenance rather than by reading an old artifact, so
/// this keeps working across the next width change without being edited — and it needs no
/// environment, so it runs in every ordinary test pass.
///
/// Version history:
///   1.0 — the 512 migration rehearsal
///   2.0 — generation-agnostic: derives from the bundled artifacts, no environment, always runs
@Suite("Vector generation migration", .serialized)
struct VectorGenerationMigrationTests {

    /// The repo root, for the gitignored shard build.
    private static var repoRoot: URL {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
    }

    /// A shard of the CURRENT generation, or `nil` when the local build is absent.
    ///
    /// `Planning/semantic-vectors/shards` is gitignored — it is regenerated by
    /// `SemanticVectorsGenerator`, byte-for-byte — so the two tests that need real vector bytes say
    /// what they skipped rather than failing on a clean checkout.
    private static func currentShard(_ volumeID: String) -> Data? {
        try? Data(contentsOf: repoRoot
            .appending(path: "Planning/semantic-vectors/shards/\(volumeID).vec"))
    }

    /// A provenance that is emphatically **not** the bundled one, standing in for the generation a
    /// device is upgrading from.
    ///
    /// Derived by halving `shippingDims`, which is a real previous configuration and, more to the
    /// point, is an input to the digest — so this is a different family by the same rule the app
    /// enforces, whatever the current width happens to be.
    private static func previousGeneration(
        of provenance: SemanticVectorsArtifacts.Provenance
    ) -> SemanticVectorsArtifacts.Provenance {
        SemanticVectorsArtifacts.Provenance(
            model: provenance.model, modelFileSHA256: provenance.modelFileSHA256,
            nativeDims: provenance.nativeDims,
            shippingDims: max(8, provenance.shippingDims / 2),
            chunkChars: provenance.chunkChars, overlapChars: provenance.overlapChars,
            prefix: provenance.prefix, pooling: provenance.pooling,
            quantization: provenance.quantization)
    }

    private static func makeDirectory() throws -> URL {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("migration-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    // MARK: - The upgrade

    @MainActor
    @Test("A device on the previous generation discards it and adopts the current one")
    func upgradeAcrossGenerations() async throws {
        await BundledSemanticVectors.prepare()
        let index = try #require(BundledSemanticVectors.index)
        let current = index.provenance
        let previous = Self.previousGeneration(of: current)
        #expect(previous.digestHex != current.digestHex, """
            Halving shippingDims did not move the provenance digest. The family rule depends on \
            width being one of its inputs; without that, two generations are indistinguishable and \
            a device would score one against the other.
            """)

        let directory = try Self.makeDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let sampleID = index.volumes[0].volumeID

        // The device as it was: a store on the old pin, with a shard on disk.
        let old = SemanticShardStore(directory: directory, provenance: previous, expectedCounts: [:])
        _ = await old.purgeIfGenerationChanged()          // stamps the old marker
        try Data(repeating: 0x5A, count: 4_096)
            .write(to: directory.appendingPathComponent("\(sampleID).vec"))
        #expect(await old.volumeIDsOnDisk().count == 1)

        // The update lands: same directory, the current pin.
        let next = SemanticShardStore(
            directory: directory, provenance: current,
            expectedCounts: Dictionary(index.volumes.map { ($0.volumeID, $0.documentCount) },
                                       uniquingKeysWith: { first, _ in first }))
        #expect(await next.purgeIfGenerationChanged() == 1, """
            A shard from the previous generation survived the change. It would then be counted as \
            present by the storage screen and refused whenever a surface asked for it — \
            indefinitely, since nothing re-fetches a shard that is already on disk.
            """)
        #expect(await next.volumeIDsOnDisk().isEmpty)

        // And the re-download works, verified against the bundled manifest.
        guard let payload = Self.currentShard(sampleID) else {
            print("[migration] no local shard build — run SemanticVectorsGenerator to exercise the "
                  + "re-download half of this test")
            return
        }
        let digest = Data(SHA256.hash(data: payload)).map { String(format: "%02x", $0) }.joined()
        StubShardProtocol.bodies = ["\(sampleID).vec": (payload, 200)]
        let fetcher = SemanticShardFetcher(
            baseURL: URL(string: "https://stub.invalid/shards")!,
            expectations: [sampleID: .init(bytes: payload.count, sha256: digest)],
            session: StubShardProtocol.makeSession())
        try await fetcher.fetchShard(for: sampleID, into: next)

        let shard = try #require(await next.shard(for: sampleID))
        #expect(shard.dims == current.shippingDims)
        #expect(shard.documentCount == index.volumes[0].documentCount)
        let anchor = try #require(shard.vector(at: 0))
        let self0 = try #require(shard.cosine(row: 0, query: anchor.codes, queryScale: anchor.scale))
        #expect(self0 > 0.99, "a document should be ~1.0 similar to itself, got \(self0)")
        print("[migration] \(sampleID): purged the old generation, adopted \(payload.count) bytes "
              + "at \(shard.dims) dims, self-similarity \(self0)")
    }

    // MARK: - The ordering constraint

    /// Publishing must precede the bundle swap, and this is what getting it backwards looks like.
    ///
    /// A bundle on generation *N* against a host still serving *N−1* pulls files of the wrong
    /// length. Pinned as a named failure so the symptom is recognisable rather than mysterious —
    /// and so the constraint lives in the artifact rather than in someone's memory of a runbook.
    @MainActor
    @Test("A bundle ahead of its host refuses every shard, by length, before anything else")
    func hostBehindBundleIsRefused() async throws {
        await BundledSemanticVectors.prepare()
        let index = try #require(BundledSemanticVectors.index)
        let sampleID = index.volumes[0].volumeID
        guard let current = Self.currentShard(sampleID) else {
            print("[migration] no local shard build — skipped")
            return
        }

        // A shorter file stands in for the previous generation's shard: at half the width it is
        // about half the size, and it is the LENGTH that is checked first.
        let stale = current.prefix(current.count / 2)
        let directory = try Self.makeDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let store = SemanticShardStore(
            directory: directory, provenance: index.provenance,
            expectedCounts: Dictionary(index.volumes.map { ($0.volumeID, $0.documentCount) },
                                       uniquingKeysWith: { first, _ in first }))

        let digest = Data(SHA256.hash(data: current)).map { String(format: "%02x", $0) }.joined()
        StubShardProtocol.bodies = ["\(sampleID).vec": (Data(stale), 200)]
        let fetcher = SemanticShardFetcher(
            baseURL: URL(string: "https://stub.invalid/shards")!,
            expectations: [sampleID: .init(bytes: current.count, sha256: digest)],
            session: StubShardProtocol.makeSession())

        await #expect(throws: (any Error).self) {
            try await fetcher.fetchShard(for: sampleID, into: store)
        }
        let recorded = await fetcher.failure(for: sampleID)
        if case .integrityMismatch = recorded {} else {
            Issue.record("expected .integrityMismatch, got \(String(describing: recorded))")
        }
        #expect(await store.volumeIDsOnDisk().isEmpty,
                "a shard that failed verification was still written to the store")
        #expect(!SemanticStorageReport.describe(try #require(recorded)).isEmpty,
                "the reader is left with a silently empty axis instead of a diagnosis")
        print("[migration] host-behind-bundle refused \(sampleID): served \(stale.count) bytes "
              + "against a \(current.count)-byte expectation")
    }

    // MARK: - The five artifacts

    /// Every bundled artifact must describe one generation.
    ///
    /// **This is the check that would have caught the map.** The 512 swap replaced the vectors, the
    /// index and the shard manifest but not the map, whose reader validates against the same pin —
    /// so the map returned `.provenanceMismatch` and the whole surface went dark, with nothing in
    /// the diff to show for it. The runbook had said the map was "unaffected by width", which was
    /// true of its placements and false of its header.
    @MainActor
    @Test("All five bundled artifacts carry one provenance digest")
    func bundledArtifactsAgree() async throws {
        await BundledSemanticVectors.prepare()
        let index = try #require(BundledSemanticVectors.index)
        let digest = index.provenance.digestHex

        let resources = Self.repoRoot.appending(path: "FRUSExplorer/Resources")
        for name in ["semantic-shards-manifest.json", "semantic-map-index.json"] {
            let data = try Data(contentsOf: resources.appending(path: name))
            let json = try #require(
                try JSONSerialization.jsonObject(with: data) as? [String: Any])
            #expect(json["provenanceDigest"] as? String == digest, """
                \(name) is from a different generation than semantic-vectors-index.json. Every \
                consumer refuses a pin it does not recognise, so this ships a dark surface rather \
                than a wrong answer — but it ships it silently.
                """)
        }
        // The binaries carry the digest in their headers, at byte 20 of both layouts.
        let expected = Data(index.provenance.digest)
        for name in ["semantic-vectors-binary.bin", "semantic-map.bin"] {
            let handle = try FileHandle(forReadingFrom: resources.appending(path: name))
            defer { try? handle.close() }
            let header = try #require(try handle.read(upToCount: 64))
            #expect(header.subdata(in: 20..<52) == expected,
                    "\(name)'s header pin disagrees with the bundled index")
        }
    }
}
