// Copyright 2026 The FRUS Explorer Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

import Foundation

// MARK: - FTS5Column

/// Names a column in the FTS5 virtual table.
///
/// Columns marked `UNINDEXED` store values in the FTS5 content shadow table but do
/// not contribute to the full-text index. Use them for identifiers and metadata that
/// must be returned with results but are never searched.
public enum FTS5Column: String, Sendable, CaseIterable {
    case documentId   = "document_id"
    case volumeId     = "volume_id"
    case documentNumber = "document_number"
    case header       = "header"
    case dateline     = "dateline"
    case sourceNote   = "source_note"
    case bodyText     = "body_text"
    case subjectTagIds = "subject_tag_ids"
    case userTagIds   = "user_tag_ids"
    case summaryText  = "summary_text"
    case noteText     = "note_text"
    case isEditorialNote = "is_editorial_note"
}

// MARK: - FTS5Schema

/// Defines the SQLite FTS5 virtual table structure and associated auxiliary tables.
///
/// `FTS5Schema` is intentionally decoupled from `FTS5Store` so the store can be
/// reused in projects with different document schemas. Pass a configured schema to
/// `FTS5Store.init` to control the table name and tokenizer.
///
/// ## External-Content Schemas
/// When `contentTable` is non-nil, the FTS5 table is created with
/// `content='<contentTable>'` and stores only the inverted index — column values are
/// read live from the content table by rowid. The content table must contain columns
/// with the same names as every FTS5 column. Index maintenance is performed by the
/// `AFTER INSERT` / `AFTER DELETE` / `AFTER UPDATE OF` triggers generated by
/// `externalContentTriggerSQL()`; direct writes through `FTS5Store` are rejected.
///
/// ## FRUS Explorer Schemas
/// - `FTS5Schema.frusDocuments` — corpus text (header, dateline, source note, body)
///   as an external-content table over `document_cache`.
/// - `FTS5Schema.userContent` — user-generated text (summaries, research notes) as a
///   separate external-content table over the same `document_cache`, so note and
///   summary edits never rewrite corpus index rows.
///
/// Version history:
///   1.0 — Session 03: initial implementation
///   2.0 — Session 2026-06-09: external-content redesign. `frusDocuments` now uses the
///          built-in `porter unicode61` tokenizer (application-layer stemming removed)
///          and reads content from `document_cache`; `userContent` schema added;
///          `createTableSQL` / `externalContentTriggerSQL` / `dropTriggerSQL` builders
///          added so the app and tests share one source of DDL truth.
public struct FTS5Schema: Sendable {

    /// Name of the FTS5 virtual table.
    public let tableName: String

    /// Ordered list of columns in the virtual table.
    public let columns: [FTS5Column]

    /// Name of the FTS5 tokenizer expression (e.g. `"porter unicode61"`).
    /// The legacy name `"frus_english"` is mapped to `"porter unicode61"` —
    /// the application-layer Porter stemming it referred to has been replaced
    /// by SQLite's built-in porter wrapper tokenizer.
    public let tokenizerName: String

    /// If non-nil, the FTS5 table is created as an external-content FTS5 table
    /// (`content=<tableName>`). Nil means a standard FTS5 table.
    public let contentTable: String?

    /// Name of the content-table column used as the FTS5 rowid mapping
    /// (`content_rowid=`). Only meaningful when `contentTable` is non-nil.
    public let contentRowid: String

    public init(
        tableName: String,
        columns: [FTS5Column],
        tokenizerName: String = "porter unicode61",
        contentTable: String? = nil,
        contentRowid: String = "rowid"
    ) {
        self.tableName = tableName
        self.columns = columns
        self.tokenizerName = tokenizerName
        self.contentTable = contentTable
        self.contentRowid = contentRowid
    }

    /// FRUS corpus document search schema.
    ///
    /// External-content FTS5 table over `document_cache`: only the inverted index is
    /// stored; all column values are read from `document_cache` at query time. The
    /// indexed columns are `header`, `dateline`, `source_note`, and `body_text`;
    /// identifier and flag columns are `UNINDEXED`. Summary and note text live in
    /// the separate `userContent` table so user edits never touch corpus rows.
    public static let frusDocuments = FTS5Schema(
        tableName: "frus_documents",
        columns: [
            .documentId, .volumeId, .documentNumber,
            .header, .dateline, .sourceNote, .bodyText,
            .subjectTagIds, .userTagIds, .isEditorialNote,
        ],
        tokenizerName: "porter unicode61",
        contentTable: "document_cache"
    )

    /// User-generated content search schema (summaries and research notes).
    ///
    /// External-content FTS5 table over the same `document_cache` rows as
    /// `frusDocuments`. Kept separate so a note or summary edit re-tokenizes only
    /// the user text, not the full document body, and so the corpus index remains
    /// immutable outside volume indexing.
    public static let userContent = FTS5Schema(
        tableName: "user_content",
        columns: [.documentId, .volumeId, .summaryText, .noteText],
        tokenizerName: "porter unicode61",
        contentTable: "document_cache"
    )

    // Columns that should be marked UNINDEXED in the CREATE VIRTUAL TABLE statement.
    static let unindexedColumns: Set<FTS5Column> = [
        .documentId, .volumeId, .documentNumber, .subjectTagIds, .userTagIds, .isEditorialNote,
    ]

    /// The columns that contribute tokens to the inverted index (i.e. not `UNINDEXED`).
    public var indexedColumns: [FTS5Column] {
        columns.filter { !Self.unindexedColumns.contains($0) }
    }

    /// The effective tokenizer expression, mapping the legacy `"frus_english"`
    /// application-layer-stemming name to the built-in porter wrapper.
    public var resolvedTokenizerName: String {
        tokenizerName == "frus_english" ? "porter unicode61" : tokenizerName
    }

    // MARK: - DDL Builders

    /// Returns the `CREATE VIRTUAL TABLE` statement for this schema.
    ///
    /// - Parameter ifNotExists: When `true`, emits `IF NOT EXISTS` so the statement
    ///   is idempotent.
    public func createTableSQL(ifNotExists: Bool) -> String {
        let columnDefs = columns.map { col -> String in
            Self.unindexedColumns.contains(col) ? "\(col.rawValue) UNINDEXED" : col.rawValue
        }.joined(separator: ",\n    ")
        let existsClause = ifNotExists ? "IF NOT EXISTS " : ""
        var options = "tokenize = '\(resolvedTokenizerName)'"
        if let content = contentTable {
            options = "content='\(content)', content_rowid='\(contentRowid)', " + options
        }
        return """
        CREATE VIRTUAL TABLE \(existsClause)\(tableName) USING fts5(
            \(columnDefs),
            \(options)
        )
        """
    }

    /// Returns the `CREATE TRIGGER` statements that keep an external-content FTS5
    /// table synchronised with its content table.
    ///
    /// Three triggers are generated (the canonical pattern from the SQLite FTS5
    /// documentation): `AFTER INSERT`, `AFTER DELETE`, and `AFTER UPDATE OF
    /// <indexed columns>`. The update trigger fires only when an *indexed* column
    /// appears in the `UPDATE` statement's `SET` list — updates that touch only
    /// `UNINDEXED` columns need no index maintenance because external-content
    /// values are read live from the content table.
    ///
    /// Returns an empty array when `contentTable` is nil.
    public func externalContentTriggerSQL() -> [String] {
        guard let content = contentTable else { return [] }
        let cols = columns.map(\.rawValue)
        let colList = cols.joined(separator: ", ")
        let newVals = cols.map { "new.\($0)" }.joined(separator: ", ")
        let oldVals = cols.map { "old.\($0)" }.joined(separator: ", ")
        let updateOf = indexedColumns.map(\.rawValue).joined(separator: ", ")
        let prefix = "\(content)_\(tableName)"
        return [
            """
            CREATE TRIGGER IF NOT EXISTS \(prefix)_ai AFTER INSERT ON \(content) BEGIN
              INSERT INTO \(tableName)(rowid, \(colList)) VALUES (new.\(contentRowid), \(newVals));
            END
            """,
            """
            CREATE TRIGGER IF NOT EXISTS \(prefix)_ad AFTER DELETE ON \(content) BEGIN
              INSERT INTO \(tableName)(\(tableName), rowid, \(colList)) VALUES('delete', old.\(contentRowid), \(oldVals));
            END
            """,
            """
            CREATE TRIGGER IF NOT EXISTS \(prefix)_au AFTER UPDATE OF \(updateOf) ON \(content) BEGIN
              INSERT INTO \(tableName)(\(tableName), rowid, \(colList)) VALUES('delete', old.\(contentRowid), \(oldVals));
              INSERT INTO \(tableName)(rowid, \(colList)) VALUES (new.\(contentRowid), \(newVals));
            END
            """,
        ]
    }

    /// Returns `DROP TRIGGER` statements for the triggers generated by
    /// `externalContentTriggerSQL()`. Used to temporarily disable index
    /// synchronisation during bulk delete-all operations.
    public func dropTriggerSQL() -> [String] {
        guard let content = contentTable else { return [] }
        let prefix = "\(content)_\(tableName)"
        return ["_ai", "_ad", "_au"].map { "DROP TRIGGER IF EXISTS \(prefix)\($0)" }
    }
}

// MARK: - FTS5Document

/// A document to be indexed in the FTS5 store.
///
/// All fields correspond directly to FTS5 virtual table columns. Nil optional fields
/// are stored as SQL NULL and are excluded from index tokenization.
///
/// The `id` field is the stable identifier used for update and delete operations.
/// It must be unique within the store.
///
/// Version history:
///   1.0 — Session 03: initial implementation
///   1.1 — Session 38: `isEditorialNote` field added
public struct FTS5Document: Sendable {
    /// Unique document identifier (e.g. `"d1"` within a volume).
    public let id: String
    /// Volume this document belongs to (e.g. `"frus1969-76v01"`).
    public let volumeId: String
    /// Printed document number from the FRUS volume, if present.
    public let documentNumber: String?
    /// Document header / title line.
    public let header: String
    /// Dateline string (place and date of authorship), if present.
    public let dateline: String?
    /// Source note describing the archival provenance, if present.
    public let sourceNote: String?
    /// Full plain-text body of the FRUS document (stripped of XML markup).
    public let bodyText: String
    /// Space-separated subject tag IDs for tag-filtered search. Nil if none.
    public let subjectTagIds: String?
    /// Space-separated user tag IDs for tag-filtered search. Nil if none.
    public let userTagIds: String?
    /// Latest generated summary text, if any summarization has been performed.
    public let summaryText: String?
    /// Research note body text, if the user has attached a note.
    public let noteText: String?
    /// Whether this document is a FRUS editorial note rather than a primary-source document.
    /// Stored as UNINDEXED in the FTS5 virtual table; not tokenized.
    public let isEditorialNote: Bool

    public init(
        id: String,
        volumeId: String,
        documentNumber: String? = nil,
        header: String,
        dateline: String? = nil,
        sourceNote: String? = nil,
        bodyText: String,
        subjectTagIds: String? = nil,
        userTagIds: String? = nil,
        summaryText: String? = nil,
        noteText: String? = nil,
        isEditorialNote: Bool = false
    ) {
        self.id = id
        self.volumeId = volumeId
        self.documentNumber = documentNumber
        self.header = header
        self.dateline = dateline
        self.sourceNote = sourceNote
        self.bodyText = bodyText
        self.subjectTagIds = subjectTagIds
        self.userTagIds = userTagIds
        self.summaryText = summaryText
        self.noteText = noteText
        self.isEditorialNote = isEditorialNote
    }
}

// MARK: - FTS5Result

/// A single full-text search result from `FTS5Store.search`.
///
/// Results are ordered by BM25 relevance score (lower = more relevant; SQLite's
/// `bm25()` function returns negative values, so sort ascending for best-first).
///
/// The `snippet` field is always an empty string. `FTS5Store.search` no longer
/// calls `snippet()` because `SearchService` replaces every snippet with TEI-derived
/// body text via `IndexingPipeline.documentBodyTextsAndDates(for:)`. Callers that
/// need a user-visible context snippet are responsible for building their own.
///
/// Version history:
///   1.0 — Session 03: initial implementation
///   1.1 — Session 38: `isEditorialNote` field added
///   1.2 — Session 123: `snippet` field is now always "" (FTS5 snippet() removed)
///   1.3 — Session 2026-06-08: `documentNumber` added so citation formatters on iOS
///          can include "Document N" in the citation string (mirrors the macOS
///          `CitationPopoverView` which already used `entry.documentNumber`).
public struct FTS5Result: Sendable {
    /// Document identifier (matches `FTS5Document.id`).
    public let documentId: String
    /// Volume this document belongs to.
    public let volumeId: String
    /// Printed document number from the FRUS volume (e.g. `"217"`), if present.
    ///
    /// Extracted during indexing from the leading integer before the first `.` in
    /// the document's `<head>` element. `nil` for editorial notes, front matter,
    /// and documents whose headers do not begin with a numeric prefix.
    public let documentNumber: String?
    /// Document header / title line.
    public let header: String
    /// Dateline, if present in the document.
    public let dateline: String?
    /// Source note, if present in the document.
    public let sourceNote: String?
    /// Context snippet with matching terms wrapped in `<b>…</b>`.
    public let snippet: String
    /// BM25 relevance score. Lower (more negative) = more relevant.
    public let bm25Score: Double
    /// Subject tag IDs associated with this document.
    public let subjectTagIds: [String]
    /// User tag IDs associated with this document.
    public let userTagIds: [String]
    /// Whether this document is an editorial note rather than a primary-source document.
    public let isEditorialNote: Bool

    /// Convenience: subject tag IDs split from the space-separated storage string.
    static func splitTagIds(_ raw: String?) -> [String] {
        guard let raw, !raw.isEmpty else { return [] }
        return raw.split(separator: " ").map(String.init)
    }
}
