#!/bin/bash
# Builds the harness from the app's REAL source files. Nothing is hand-copied: the only app code
# not passed to swiftc by path is DocumentView.extractYear, a static on a SwiftUI View that cannot
# be compiled alone; it is cut out of DocumentView.swift by awk and checked identical (modulo
# whitespace) to MacDocumentView.extractYear before use.
set -euo pipefail
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
REPO=${SRCROOT:?}
H="$(cd "$(dirname "$0")" && pwd)"
cd "$H"

extract() { awk '/static func extractYear\(from dateline: String\?\) -> Int\? \{/{f=1} f{print} f&&/^    }$/{exit}' "$1"; }
extract "$REPO/FRUSExplorer/DocumentView/DocumentView.swift" > gen_ios_extractYear.txt
extract "$REPO/FRUSExplorer/App/MacDocumentView.swift"       > gen_mac_extractYear.txt
if ! diff <(tr -d ' \n\t' < gen_ios_extractYear.txt) <(tr -d ' \n\t' < gen_mac_extractYear.txt) >/dev/null; then
  echo "extractYear differs between DocumentView and MacDocumentView"; exit 1
fi
[ -s gen_ios_extractYear.txt ] || { echo "extractYear not found"; exit 1; }
{ echo "import Foundation"; echo "// GENERATED by build.sh from DocumentView.swift"; echo "enum AppYearGate {"; cat gen_ios_extractYear.txt; echo "}"; } > GeneratedYearGate.swift

SRC=(
  "$REPO/FRUSExplorer/SourceExplorer/CentralFilesClassifier.swift"
  "$REPO/FRUSExplorer/SourceExplorer/CentralFilesIndex.swift"
  "$REPO/FRUSExplorer/SourceExplorer/GeoKeyNormalizer.swift"
  "$REPO/FRUSExplorer/Browser/VolumeStructure.swift"
  "$REPO/FRUSExplorer/Models/Manifest/ManifestModels.swift"
)
shasum -a 256 "${SRC[@]}" gen_ios_extractYear.txt > source-sha256.txt
xcrun swiftc -O ${SWIFT_MODE:-} "${SRC[@]}" Stubs.swift GeneratedYearGate.swift main.swift -o harness
# CentralFilesIndexStore loads through Bundle.main; for a command-line tool that is the binary's dir.
ln -sf "$REPO/FRUSExplorer/Resources/central-files-index.json" central-files-index.json
echo "built $H/harness"
